sudo: required
services:
  - docker

before_install:
  - docker build -t lwilson99/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run lwilson99/react-test npm test -- --coverage

after_success:
  - docker build -t lwilson99/multi-client ./client
  - docker build -t lwilson99/multi-nginx ./nginx
  - docker build -t lwilson99/multi-server ./server
  - docker build -t lwilson99/multi-worker ./worker
  # login
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # take image and put to dockerhub
  - docker push lwilson99/multi-client
  - docker push lwilson99/multi-nginx
  - docker push lwilson99/multi-server
  - docker push lwilson99/multi-worker
  
